const fonts = {
    Manrope: {
        Bold: 'Manrope-Bold',
        ExtraBold: 'Manrope-ExtraBold',
        ExtraLight: 'Manrope-ExtraLight',
        Light: 'Manrope-Light',
        Medium: 'Manrope-Medium',
        Regular: 'Manrope-Regular',
        SemiBold: 'Manrope-SemiBold',
    },
    Montserrat: {
        Black: 'Montserrat-Black',
        BlackItalic: 'Montserrat-BlackItalic',
        Bold: 'Montserrat-Bold',
        BoldItalic: 'Montserrat-BoldItalic',
        ExtraBold: 'Montserrat-ExtraBold',
        ExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
        ExtraLight: 'Montserrat-ExtraLight',
        ExtraLightItalic: 'Montserrat-ExtraLightItalic',
        Italic: 'Montserrat-Italic',
        Light: 'Montserrat-Light',
        LightItalic: 'Montserrat-LightItalic',
        Medium: 'Montserrat-Medium',
        MediumItalic: 'Montserrat-MediumItalic',
        Regular: 'Montserrat-Regular',
        SemiBold: 'Montserrat-SemiBold',
        SemiBoldItalic: 'Montserrat-SemiBoldItalic',
        Thin: 'Montserrat-Thin',
        ThinItalic: 'Montserrat-ThinItalic',
    },
    NotoSansSC: {
        Black: 'NotoSansSC-Black',
        Bold: 'NotoSansSC-Bold',
        Light: 'NotoSansSC-Light',
        Medium: 'NotoSansSC-Medium',
        Regular: 'NotoSansSC-Regular',
        Thin: 'NotoSansSC-Thin',
    },
    ReadexPro: {
        Bold: 'ReadexPro-Bold',
        ExtraLight: 'ReadexPro-ExtraLight',
        Light: 'ReadexPro-Light',
        Medium: 'ReadexPro-Medium',
        Regular: 'ReadexPro-Regular',
        SemiBold: 'ReadexPro-SemiBold',
    },
    Roboto: {
        Black: 'Roboto-Black',
        BlackItalic: 'Roboto-BlackItalic',
        Bold: 'Roboto-Bold',
        BoldItalic: 'Roboto-BoldItalic',
        Italic: 'Roboto-Italic',
        Light: 'Roboto-Light',
        LightItalic: 'Roboto-LightItalic',
        Medium: 'Roboto-Medium',
        MediumItalic: 'Roboto-MediumItalic',
        Regular: 'Roboto-Regular',
        Thin: 'Roboto-Thin',
        ThinItalic: 'Roboto-ThinItalic',
    },
    SourceHanSerifSC: {
        Bold: 'SourceHanSerifSC-Bold',
        ExtraLight: 'SourceHanSerifSC-ExtraLight',
        Heavy: 'SourceHanSerifSC-Heavy',
        Light: 'SourceHanSerifSC-Light',
        Medium: 'SourceHanSerifSC-Medium',
        Regular: 'SourceHanSerifSC-Regular',
        SemiBold: 'SourceHanSerifSC-SemiBold',
    },
    SourceHanSansCN: {
        Bold: 'SourceHanSansCN-Bold',
        ExtraLight: 'SourceHanSansCN-ExtraLight',
        Heavy: 'SourceHanSansCN-Heavy',
        Light: 'SourceHanSansCN-Light',
        Medium: 'SourceHanSansCN-Medium',
        Normal: 'SourceHanSansCN-Normal',
        Regular: 'SourceHanSansCN-Regular',
    },
};

export default fonts;
